name: clean

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency: preview-${{ github.ref }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Clean preview
        uses: rossjrw/pr-preview-action@v1
  pages:
    needs: preview
    uses: ./.github/workflows/pages.yml
